### ISSUE TITLE
Documentation site is broken with Chrome 71

### ISSUE THREAD

**Issue by niahoo** [uber/react-vis#1006]
Try to read this page : https://uber.github.io/react-vis/documentation/general-principles and you will end up here : https://uber.github.io/react-vis/documentation/welcome-to-react-vis .

I'm using Chrome  71.0.3573.0

**Comment by mcnuttandrew** [comment]
@jckr or someone who does ocular things wanna take a look at this?

**Comment by andrewkusuma** [comment]
I'm using Safari Version 12.0 (13606.2.11) and have same problem

**Comment by CAYdenberg** [comment]
This seems to be an issue with Ocular, but if you remove the "Welcome to React-vis" component from https://github.com/uber/react-vis/blob/master/website/src/mdRoutes.js#L138 the menu works correctly. I'm guessing it can't handle having both a first-level child (to present the main view) and children to present the submenu.

**Comment by jckr** [comment]
thanks for bringing that up. taking a look

**Comment by jckr** [comment]
ok so - I'm upgrading the version of ocular and uploading new docs. 
The routes file that @CAYdenberg referenced has been compiled under an older version of ocular. At this time, links to a section of the docs (ie https://uber.github.io/react-vis/documentation/general-principles) were honored. Ocular has evolved since then - some of the documentation websites it generated have a flat structure, some have 1 level, some have many, and we found that the existing behavior (link to a section would go down until the first page of actual documentation is found) was ambiguous. So from now on only links to actual documentation pages were honored. (ie https://uber.github.io/react-vis/documentation/general-principles/scales-and-data) 

Some versions of ocular following that decision were not too good at handling route files made in the older version. That was all well and good as long as the version of ocular on react-vis wasn't upgraded. But it has, so in some circumstances the table of contents could stop working. 

After upgrading, 
https://uber.github.io/react-vis/documentation/general-principles will still just point to the first page of react-vis doc, but https://uber.github.io/react-vis/documentation/general-principles/scales-and-data works and table of contents work in any circumstance. Will close but feel free to reopen if that doesn't work for you

**Comment by niahoo** [comment]
It seems good ! Thank you.
