### ISSUE TITLE
Dual-Axis Charts

### ISSUE THREAD

**Issue by waywaaard** [uber/react-vis#131]
I am not sure it this is a uber requirement or not, but it is useful for multi line charts with different scales.

Example: http://www.highcharts.com/demo/combo-dual-axes

**Comment by bulyonov** [comment]
Hey @waywaaard , you can solve your problem in this way:

```jsx
<XYPlot>
  <YAxis orientation="left" title="Value one" />
  <YAxis orientation="right" title="Value two" />
</XYPlot>
```

You might also need to pass a different domain and range for the axis. Please take a look at [the docs for axes components](https://github.com/uber/react-vis/blob/master/docs/xy-plot.md#axes) and at [the docs for scales](https://github.com/uber/react-vis/blob/master/docs/scales-and-data.md#scale-properties) for that.

**Comment by waywaaard** [comment]
Hm, I tried this but the second axis was misaligned.

**Comment by jabaren** [comment]
Hi
I have 2 question:

The former question is:

I would like to create a chart with multiple axes, I already did it 

VerticalBarSeries:  data={[
                {x: 1, y: 3},
                {x: 2, y: 5},
                {x: 3, y: 15}
              ]}

LineSeries:  data={[
                {x: 1, y: 10},
                {x: 2, y: 2},
                {x: 3, y: 15}
              ]}


![image](https://cloud.githubusercontent.com/assets/9442532/23668654/661f9590-0327-11e7-9d85-d219612f2e87.png)

but my expected behavior is manage diferent values for the right yAxis and left yAxis, then put them (the charts) in the same position:

VerticalBarSeries:  data={[
                {x: 1, y: 3},
                {x: 2, y: 5},
                {x: 3, y: 15}
              ]}

LineSeries: data={[
                {x: 10, y: 10},
                {x: 20, y: 2},
                {x: 30, y: 15}
              ]}

![image](https://cloud.githubusercontent.com/assets/9442532/23669455/d8a89394-0329-11e7-8c1c-9e7bc43b03f7.png)

but my expected result should be such as:

![image](https://cloud.githubusercontent.com/assets/9442532/23669499/fd077908-0329-11e7-912b-dc81dfcb3e04.png)



Last question is:

How could I draw in the correct space the right yAxes, now the style 

svg:not(:root) {
    overflow: hidden;
}

hides the right axis, I fixed using overflow:visible. Is there another way to fix it?

i.e.

with svg:not(:root) {    overflow: hidden;  }
![image](https://cloud.githubusercontent.com/assets/9442532/23669265/2561582a-0329-11e7-9ead-e6bf0cb48555.png)

with svg:not(:root) {    overflow: visible;  }
![image](https://cloud.githubusercontent.com/assets/9442532/23669769/02e7320e-032b-11e7-9afc-5dde08f5b7ca.png)

**Comment by mcnuttandrew** [comment]
Hey @jabaren 
It looks like you need more margin: {right} on your XYPlot?

**Comment by jabaren** [comment]
@mcnuttandrew let me check that property on XYPlot, thanks
