### ISSUE TITLE
Cookbook style documentation

### ISSUE THREAD

**Issue by mcnuttandrew** [uber/react-vis#213]

**Comment by chrisirhc** [comment]
Any updates on this?

**Comment by alee8** [comment]
Curious as to what this entails.  Will this be done by external resource or
are there plans to draw on internal resources.
I previously offered to assist if it is all internal and within our group.

Alison

**Comment by amilajack** [comment]
@chrisirhc I think that this should be done after the gh-pages documentation refactor. That will make this step a lot easier since the examples that we can use will done. Maybe we can just borrow those example and add them to a live editor, like [FormidableLabs/component-playground](https://github.com/FormidableLabs/component-playground). Thoughts?

**Comment by amilajack** [comment]
Do these examples need to be editable?

**Comment by mcnuttandrew** [comment]
It seems like we went a different direction on the docs, marking as closed?
