### ISSUE TITLE
Muti series and Y Axes, how to use map and scale

### ISSUE THREAD

**Issue by nichliu** [uber/react-vis#388]
Hi, I have 2 line series and 2 Y axes, but I don't know how to bind each line series to different Y axes

Here is my code
```javascript
<XYPlot
    width={1000}
    height={600}>
    <HorizontalGridLines />
    <LineSeries data={this.props.temperature} />
    <XAxis title="Time" tickFormat={tickFormatter} />
    <YAxis title="Temperature" />
    <LineSeries data={this.props.pressure} />
    <YAxis title="Pressure" orientation="right" />
</XYPlot>
```

**Comment by mcnuttandrew** [comment]
Hey @nichliu 

Unfortunately there isn't a straight forward way to bind axes to series. The core thing to know about the XYplot is that is projecting a coordinate system underneath your data and all marks made in it will adhere to that coordinate system. Said XY coordinate system is formed by looking at the domain of the data for each of the series. In order to make your data appear as you wish in a multiple y-axis type series you will have to modify your data and specify the tick values for each YAxis. Here is a rough sketch on the technique:

- "Non-dimensionalize" your data: begin by rescaling your data so that y values exist in the range that you wish to shows them. Eg if you have temperatures that go from [50, 97], and pressures that go from [1, 10], you might rescale them to [0, 1]. This will allow them to be expressed in a common zone. (we are referring to this as nondimensionalization, in a hand-wavy kind of way because you are stripping the variables of their hypothetically physical meaning in order to manipulate them computationally). Once all of your yValues exisit in this band [0, 1], it will be easy to compare them.

- Specify your YAxis tick values: The new artificial coordinate domain will not be meaningful to your reader, so you project the values into your desired coordiantes (temperature, pressure, etc). 

```javascript
<YAxis tickValues={[0, 1, 2, 3, 4]}>
```
Alternatively if you used a function to rescale your data you can also invert it and use tickFormat.

I am assuming your data sets are properly formatted for LineSeries ([{x: 1, y: 1}, ...] etc). There is some additional discussion in #131. Now that we've said all that, indulge me in a *Data Visualizationist Nit Pick*: Dual y-axis charts are [bad news](http://www.storytellingwithdata.com/blog/2016/2/1/be-gone-dual-y-axis), they obscure information and can easily be replaced by small multiples.

**Comment by mcnuttandrew** [comment]
I'm gonna close this, but feel free to re-open if this doesn't address you question

**Comment by nichliu** [comment]
Hi, @mcnuttandrew 

I did rescale all my data range from 0-1,  the chart scale still min/max of my readings value provided, not from 0-1
![screen shot 2017-04-16 at 8 34 20 am](https://cloud.githubusercontent.com/assets/4934001/25071901/a0796c6c-227f-11e7-910e-03a6a6439c3e.png)


 then I setup 
<YAxis tickValues={[0, 1, 2, 3, 4]}>
But on chart, the new tickValues never show up, 
![screen shot 2017-04-16 at 8 36 05 am](https://cloud.githubusercontent.com/assets/4934001/25071909/c9660a4a-227f-11e7-8e96-22b268bf3755.png)

**Comment by mcnuttandrew** [comment]
Can you provide a sample of your data? Also can you provide your updated code?

**Comment by nichliu** [comment]
@mcnuttandrew 

Here is my code
                <XYPlot width={1000} height={600} yDomain={[0,70]} legends={["Test2","Test1"]}  >
                    <XAxis title="Time" tickFormat={tickFormatter} />
                    <YAxis tickValues={[0,10,20,30,40,50,60]}  title="Temperature" />
                    <LineSeries  data={this.props.readings} color="red" format={this.showTemperatureDetail}   />
                    <YAxis  tickValues={[10,20,30,40,50,60,70]}  title="&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Humidity" orientation="right"  />
                    <LineSeries  data={this.props.sensorHumidityData} color="blue"   />
                </XYPlot>

My data just like
[{x: 1492450301,y:23},{x: 1492450328,y:21.5}]

Right now the chart scale is working, tickValues on left side yAxis is working, but tickValues on second yAxis, right side of the chart are not show up. Here is my screen shot

![screen shot 2017-04-17 at 11 29 12](https://cloud.githubusercontent.com/assets/4934001/25097433/c36ce900-2361-11e7-946d-0177d0b34dd5.png)

**Comment by mcnuttandrew** [comment]
So my comment about rescaling your data is a little bit different. Because your two data sets are unrelated, it is necessary to move them into a common domain. This can be anything, as long it looks correct to you. Specifically, I am suggesting your data should be formatted like:

```javascript
data = [{x: 1492450301,y:1},{x: 1492450328,y:0}]
```

then your whole chart should look something like

```javascript
<XYPlot width={1000} height={1000} >
<XAxis />
<YAxis tickFormat={tick => RESCALING_FUNCTION_FOR_PRESSURE(tick)}/>
<YAxis tickFormat={tick => RESCALING_FUNCTION_FOR_TEMPERATURE(tick)} right={10}/>
<LineSeries data={data1} />
<LineSeries data={data2} />
</XYPlot>
```

**Comment by nichliu** [comment]
@mcnuttandrew 

I got error said

Uncaught ReferenceError: RESCALING_FUNCTION_FOR_PRESSURE is not defined

**Comment by mindjuice** [comment]
Instead of rescaling all my data, I just made two graphs and positioned them over top of each other with one YAxis on the left and the other YAxis on the right.  Only one has an XAxis.  Essentially the following:

```
<div style={{ position: 'relative' }}>
  <div>
    <XYPlot height={400} width={730} margin={{ left: 90, right: 90, bottom: 70 }}>
      <VerticalGridLines />
      <HorizontalGridLines />
      <XAxis />
      <YAxis />
      <LineSeries data={this.props.data1} color="green" />
    </XYPlot>
  </div>
  <div style={{ position: 'absolute', top: 0 }}>
    <XYPlot height={400} width={730} margin={{ left: 90, right: 90, bottom: 70 }}>
      <YAxis orientation="right"/>
      <LineSeries data={this.props.data2} color="blue"/>
    </XYPlot>
  </div>
</div>
```

You can see it live here: https://goo.gl/o8YC7Y

**Comment by gerardvanderput** [comment]
Excellent answer by @mcnuttandrew. However, you don't necessarily have to take away the dimension from your original y-axis. 

Let's assume you have to y-axes, and one x-axis. We will display our original y-axis on the left and call this range **yDomain**. The y-axis on the right we call **cDomain** (c = custom).

Each of our domains have a **start** and **end** value. We'll refer to them as `yDomain.start`, `cDomain.end`, etc. Each domain also represents a **range** which can be calculated by `yDomain.start - yDomain.end` ( = **yDomain.range** ) resp. `cDomain.start - cDomain.end` ( = **cDomain.range** ).

We also have a **factor** which represents the relationship between the two ranges = `yDomain.range / cDomain.range`.

As Andrew mentioned, the graph has a coordinate system which is based on our yDomain, and xDomain. And we will keep it like that. With the variables above, we can translate values from yDomain > cDomain, and visa versa:

**yDomain.value > cDomain.value**
cDomain.value (**m**) = yDomain.start + ((yDomain.value - cDomain.start) * factor)

And the other way around:
**cDomain.value > yDomain.value**
yDomain.value (**n**) = ((cDomain.value - yDomain.start) / factor) + cDomain.start

Make sure to:
- translate your original cDomain values to yDomain values with the n-formula, before passing them as data to your chart
- translate the tickFormat ( = React component property) of the cDomain y-axis values with the m-formula.

And you're good to go :+1: PS draw the above on paper and it will make more sense!

**Comment by ayepRahman** [comment]
@gerardvanderput , do you have an example for the solution you have mention?

**Comment by gerardvanderput** [comment]
> @gerardvanderput , do you have an example for the solution you have mention?

@ayepRahman Sorry, I don't. However, the comment I wrote earlier is very detailed so you should be able to create a solution yourself?

**Comment by rvodden** [comment]
@ayepRahman I've just made this work and uploaded the gist here:

https://gist.github.com/rvodden/dc841928d8c24ef28026395a88ff63d3

Note that this assumes that the minimum of the 2nd y-axis is zero.

**Comment by octaviolage** [comment]
@ayepRahman 
I made an example following @gerardvanderput tip

```js
import React from 'react';

import { XYPlot, XAxis, YAxis, VerticalBarSeries, LineSeries } from 'react-vis';
import 'react-vis/dist/style.css';

export const Example = (props) => {
  
  // Line data
  const avgPriceMonthly = [
    {x: 'June', y: 45},
    {x: 'July', y: 24},
    {x: 'August', y: 30},
    {x: 'September', y: 40},
    {x: 'October', y: 33}
  ]

  // Bar data
  const monthlySales = [
    {x: 'June', y: 1200},
    {x: 'July', y: 650},
    {x: 'August', y: 1100},
    {x: 'September', y: 750},
    {x: 'October', y: 1470}
  ]

  // Function to convert scale to another axis Y
  const handleCustomScale = (tick) => { // Can be add a customStart parameter to sum with total 
    //                                     if scales doesn't start at same point
    const maxSalesValue = Math.max(...monthlySales.map(item => item.y)); // Get max value from sales data
    const maxPriceValue = Math.max(...avgPriceMonthly.map(item => item.y)); // Get max value from prices data
    const factor = maxSalesValue / maxPriceValue; // Calculate factor to convert sales tick to price tick
    return Math.round(tick / factor); // Return result as a integer
  }

  return (
    <XYPlot 
      margin={{bottom: 70, left: 70, right: 70}} // Need to add margin to make space for the scale
      xType="ordinal" 
      width={600} height={300}>
      <VerticalBarSeries
        barWidth={0.5}
        data={monthlySales}
        color='#15b7f7'
      />
      <LineSeries
        yDomain={[0, Math.max(...avgPriceMonthly.map(item => item.y))]} // Get the max value of the line data
        data={avgPriceMonthly}
        color='#df4747'
        />
      <XAxis tickLabelAngle={-45} />
      <YAxis /> 
      <YAxis orientation='right' tickTotal={5} tickFormat={v => handleCustomScale(v)} /> 
    </XYPlot>
  );
}

export default Example;
```

Result is:
<div align="center">
  <img align="center" src="https://uploaddeimagens.com.br/images/003/437/129/full/Screenshot_1.png?1631935815" />
<div>
