### ISSUE TITLE
PolygonSeries leaks over XAxis Labels

### ISSUE THREAD

**Issue by Smarq** [uber/react-vis#407]
Hello,

I am having an issue with the PolygonSeries running over the XAxis labels. Here is my code: 
```
<XYPlot
     xType="linear"
     width={800}
     height={500}
     yDomain={[minPrice - stdDeviation, maxPrice + stdDeviation]}
     margin={{ left: 100, right: 100 }}>
     <PolygonSeries
          data={[
                { x: minMileage, y: minPrice - stdDeviation },
                { x: minMileage, y: maxPrice + stdDeviation },
                { x: maxMileage, y: maxPrice + stdDeviation },
                { x: maxMileage, y: minPrice - stdDeviation }
         ]}
         color="#f5f5f5" />
     <PolygonSeries
            data={getPriceBand(slope, yIntercept, minMileage, maxMileage, stdDeviation, 3.2, 2)}
            color="#f3b8af" />
     <PolygonSeries
            data={getPriceBand(slope, yIntercept, minMileage, maxMileage, stdDeviation, -2, -3.2)}
            color="#d5b5f2" />
     <VerticalGridLines tickTotal={5} />
     <HorizontalGridLines tickTotal={5} />
     <LineSeries
         data={ targetLine }
         color="darkGreen"/>
     <MarkSeries
             data={data}
             color="redOrange">
     </MarkSeries>
     <XAxis />
     <YAxis />
</XYPlot>
```
Which produces the following screenshot:

![screen shot 2017-05-03 at 9 54 44 am](https://cloud.githubusercontent.com/assets/2789511/25666589/966c17fa-2fe6-11e7-8804-061c258bc34d.png)

Ultimately, I believe that changing the yDomain is causing this issue. The feature I am trying to implement is a zoom and I was hoping to be able to do that using xDomain and yDomain.

**Comment by LoicUV** [comment]
I have a similar problem using `xDomain` with a line & area series where the data overflows the axis.
I think applying a domain should strip the data that is outside of the domain.

![overflow](https://cloud.githubusercontent.com/assets/592542/25706492/e5b51d0c-30e0-11e7-959b-e303e65a307e.png)

**Comment by mcnuttandrew** [comment]
Hey @Smarq 

You've hit upon a complex issue! While it would make sense for the chart to crop anything outside of it's innerWidth/innerHeight, that can lead to weird looking side effects like dots being cut in half etc.

Instead, there are couple of ways that you could address this in 1.5.0. You could either use gradientDefs (https://github.com/uber/react-vis/blob/master/docs/markdown/gradients.md) and clippaths for the most precise control, or you could use the Borders component (https://github.com/uber/react-vis/blob/master/docs/markdown/borders.md), which allows you to style the margins of the chart. I think these two stratagies should resolve this ticket, but if you feel otherwise feel free to re-open.

**Comment by jpoeppel** [comment]
@mcnuttandrew The border component works well for SVG drawings. Is there a similar trick one can use when using the Canvas-Versions Series?

**Comment by mcnuttandrew** [comment]
@jpoeppel not as of yet! But you could certainly make an addition the library to make that happen! Either a BordersCanvas, which would just draw on the canvas directly, or a BordersDOM (as dom elements appear above canvas ones).
