### ISSUE TITLE
null values in the data object

### ISSUE THREAD

**Issue by tijp** [uber/react-vis#457]
Hey,

First of all I want to thank you all for this amazing library!

Currently I'm trying to visualise data with `null` values. The data is extracted from diesel generators, and `null` values means the generator is either turned off at that moment, or there is no connection.
I understand from this comment https://github.com/uber/react-vis/issues/109#issuecomment-248211411 that null values will be automatically converted to zeros, however in this use case that would mean the generator is turned on, but not outputting any power. Zeros are different than `null`'s.

An example dataset could be:
`const data = [{x: 0, y: 10}, {x: 1, y: 11}, {x: 2, y: null}, {x: 3, y: 13}, {x: 4, y: 14}];`

Which looks like this (`null` is changed to 0, y-axis doesn't scale well?):
![image](https://user-images.githubusercontent.com/9055401/27287044-bd58b116-5502-11e7-9cf3-078acac65184.png)

What I'm trying to achieve is the following:
![image](https://user-images.githubusercontent.com/9055401/27289292-b70eb0ec-5509-11e7-88b1-8791512dc0e3.png)

The only way I managed to accomplish this, is by changing the _renderLine function in the source code of line-series (and some other series for it to work as well, like line-mark-series) from this:
[`line = line.x(x).y(y);`](https://github.com/uber/react-vis/blob/master/src/plot/series/line-series.js#L66)

to this:
`line = line.x(x).y(y).defined((d) => d.y !== null);`

However I'm quoting from the comment I just mentioned

> We want the user to provide well structured data and deal with such corner cases as null or undefined values of objects (currently they will be treated as zeros).

What would be the best way to deal with this without changing the source code. Or is there currently no way (and would you accept such a pull request?)

Thank you very much!

**Comment by ericsoco** [comment]
Agreed we should be using [`line.defined()`](https://github.com/d3/d3-shape#line_defined) when null/undefined values are possible for a given dataset. More broadly, the idea of accessors instead of just directly reading each datum is nice, but I don't know much about how data are cached and what the impact would be of either of the above...

**Comment by mcnuttandrew** [comment]
Hey @tijp 

The quickest/dirtiest workaround will be for you to split your data at every null and introduce a new line series for each continuous section of data, which would be the spirit of the comment that you are highlighting. However, this is clearly not an ideal solution! We would gladly accept PR adding defined to renderLine. I'd suggest a prop on LineSeries called defined that accepts a function or a string (same pattern as curve). 

(also @ericsoco there's an open issue for accessors here at #360)

**Comment by tijp** [comment]
Cool!

Currently I don't have much time.
In 2-3 days I'll have more time and will make a PR.

**Comment by jckr** [comment]
I think the larger issue is that the lineSeries treats a series of datapoint the same way that other ...Series treat a single datapoint - as the smallest atomic object. We can't pass data per datapoint (ie stroke-dasharray, thickness, color...) and have to do this at the level of the line.
What we could do is create a segmentSeries that, instead of generating a <path />, would generate a number of <line /> elements which could all be accessed and manipulated. such a series could deal with missing values.

**Comment by CharukaK** [comment]
I'm also interested in this feature, as @mcnuttandrew mentioned here in the [comment](https://github.com/uber/react-vis/issues/457#issuecomment-309494756), is this the only work around for the problem? it will be really useful if this feature was included in the library

**Comment by tijp** [comment]
Hey,

Sorry I never created a PR for this.
I will try to do this today.

**Comment by mcnuttandrew** [comment]
The solution to this is in!

**Comment by girlslearningcodeyul** [comment]
is this still supported? or has the accessor been renamed?

**Comment by NeroVanbiervliet** [comment]
the property has been renamed to `getNull`
