### ISSUE TITLE
Unexpected Area chart rendering

### ISSUE THREAD

**Issue by ajainarayanan** [uber/react-vis#507]
I'm trying to render Area Chart + Mark Series and I'm running into a case where I have datapoints with same `y` values. For some reason react-vis area chart is just displaying a line ending in the middle. The same with d3 seems to work fine.

Here is the problem i'm seeing,
React-vis example: https://www.webpackbin.com/bins/-KoVm5udhH58CbwxUmaQ
D3-example: https://codepen.io/ajainarayanan/pen/gRBPNB?editors=0110

Not sure if I'm doing something wrong or if its a known issue (xDomain not being used to calculate `x`, `y` and `y0` props for `d3.area`)

**Comment by ajainarayanan** [comment]
One more problem that I noticed is y-axis ticks. I have another chart in the same webpack bin example which has y values set to 0 and yDomain set to `[0, 10]`. When the chart is rendered what I expected was to have data points on the x-axis however all the values are mapped to `10` even though the `y` values are 0. 

Not sure if its related but I have seen this in just `MarkSeries` and `BarSeries` too.

**Comment by jckr** [comment]
you have to put your yDomain at the plot level.
ie: 

`<FPlot
        height={300}
        style={{'margin-top': '50px'}}
        xDomain={[0, 3]}
        yDomain={[0, 10]}
      ><YAxis />  `

instead of `<FPlot
        height={300}
        style={{'margin-top': '50px'}}
        xDomain={[0, 3]}
      ><YAxis 
yDomain={[0, 10]}
/>  `

What's going on in your current example is that the yDomain is computed from the data. your y values are all 10, so the minimum and maximum are 10 and the yDomain for the plot is [10, 10]. 
unless you specify a domain at the plot level or at the series level, for all series the domain will be [10, 10]. 
You did specify a domain for your yAxis, so this one goes from 0 to 10. but that doesn't impact the yDomain of the rest of the chart. indeed, you could want to have a different domain for your axis (or for a given series) than for the rest of the chart. 
yDomain only goes down - so you can specify it on the plot level, or on each series, or it can be deduced from the data.

**Comment by ajainarayanan** [comment]
@jckr Ah! That makes sense. Thanks for the correction on yDomain

**Comment by jckr** [comment]
that should address both your issues btw. It's the same cause for your 2nd chart. the yDomain for that series is [10,10] so the y-position is, arbitrarily, to the top of the range.

**Comment by ajainarayanan** [comment]
@jckr Yes. Thanks a lot for the help! I am closing this issue.
