### ISSUE TITLE
Time series in Unix vs. ISO

### ISSUE THREAD

**Issue by pcmaffey** [uber/react-vis#509]
The docs for Time series point to https://github.com/d3/d3-scale/blob/master/README.md#time-scales, which uses Date objects. 

But the time-chart example uses unix timestamps, which are numbers vs. objects.

ISO date objects work in Area and LineSeries components (so far), but I get 'invalid propType warnings, expected Number but received Date' for LabelSeries, Crosshair, DecorativeAxis, etc.

**Comment by jckr** [comment]
thanks for raising this. You are right, there's an inconsistency in what can be passed as x or y properties across the board, some series accept anything, while other elements require a number or a number or a string. Will fix in next release

**Comment by jckr** [comment]
See #586. Closing as well

**Comment by jbach** [comment]
Date objects as `x` do work with LabelSeries, for example. But the `Invalid propType` warning still persists, as `x` is typed as [`number`/`string`](https://github.com/uber/react-vis/blob/master/src/plot/series/label-series.js#L125). I reckon this is just a propTyping issue or is this expected behaviour?
