### ISSUE TITLE
Moving away from SCSS

### ISSUE THREAD

**Issue by NameFILIP** [uber/react-vis#534]
Are there any plans to move away from SCSS to avoid the `@import ...` styles step? Having SCSS as a dependency only to use the charting library is not ideal for projects which don't use SCSS.

Inline styles or `styled-components` would be a good alternative.

**Comment by mcnuttandrew** [comment]
We've talked about this before, and maybe now is the time to completely switch over to inline styles as we've been in a mixed context (of some inline/some stylesheet) for a while. I think in order to complete this task the styling system would need to be added to the legends, refined in the treemap and radial chart.

All that is to say, i think this should be totally possible. I would push against use styled-components as we already have quite a bit of investment in inline styling, but I would hear other opinions.

**Comment by jckr** [comment]
I'm personally happy with the current situation which doesn't mean I can't be convinced otherwise. 

Right now, react-vis components look and feel can be controlled in many ways:
- through the props which are exposed (ie color for a series),
- by passing a style prop - for added flexibility, and this is pretty close to having inline styles,
- through external style sheets / scss. 

So it's correct that today to have the default react-vis styles some kind of linking to the react-vis stylesheet must take place. that's one extra step and while in certain build systems it's relatively painless in others it's more of a hassle. 

However, if we were to move to inline styles, then users would no longer have the possibility to change look and feel via external style sheets. or it would be extra complicated and hacky. 

imo styling through style sheets, if not the only way to control look and feel of charts, is still a pretty valid approach. 

so that's where i stand on this

**Comment by alee8** [comment]
How about considering CSS Level 3 to replace the features using SCSS?

**Comment by mcnuttandrew** [comment]
@alee8 can you say more about that? the react-vis style sheet is already exported as a plain css file? I guess note of pedantry, that style sheet could be imported via html (thus preventing the need for adding scss compilation to a project that wouldn't have it by default)?

**Comment by borisrorsvort** [comment]
Inline styles library are legions, what about people who are already constrained by one? 

For reference, Material-ui makes a good case for styling solution interop https://material-ui-1dab0.firebaseapp.com/guides/interoperability/
