### ISSUE TITLE
very basic bar chart doesn't work

### ISSUE THREAD

**Issue by codyc4321** [uber/react-vis#538]
Can't even make a basic bar chart with this

**Comment by mcnuttandrew** [comment]
Hey @codyc4321 

Sorry to hear you are having trouble. There are a wide variety of ways to make a bar chart in react-vis. The general approach is to use an XYPlot and then embed whatever type of series is appropriate (VerticalBarSeries is appropriate for bar charts and VerticalRectSeries is appropriate for histograms). (documentation [here](http://uber.github.io/react-vis/#/documentation/series-reference/bar-series))

That said, if you are writing with an issue I imagine you've already seen that? Can you provide some example code/data so that I can point you in the right direction?

**Comment by mcnuttandrew** [comment]
I'm going to close this issue, as I don't have enough information to move forward (either in help or on bug fixes) but feel free to re-open or continue the discussion under the close
