### ISSUE TITLE
Fix Axis range to start at 0

### ISSUE THREAD

**Issue by cmtoomey** [uber/react-vis#609]
Is there a way to fix an axis to start at 0, regardless of the range of data passed into the chart? It appears that both [name]Domain and [name]Range require arrays, but as the data changes I'm not going to have access to the local max to set to the end of the array.

**Comment by mcnuttandrew** [comment]
Hey @cmtoomey,

Unfortunately there isn't a way to set just one of the two ends of the domain or range. I've run into this problem as well, however in a fit of short sightedness I didn't think to add something to the library. I could imagine a PR where we accept a symbol (something like DOMAIN_MAX or RANGE_MIN) as one of the arguments, or even more minimally allow users to pass stuff like [undefined, 10]. If that sounds like a interesting project to you, I would gladly welcome a PR.

In the meantime you probably want quicker answers. In the past I've wrapper my react-vis components in a light caching layer so that metadata, such as the domain of the data, is computed one when appropriate. But that might be overkill for your project, so I'd suggest that scanning your data with a min/max check at render time is maybe not the end of the world. Dropping something in like

```javascript
const {xMin, xMax} = data.reduce((acc, row) => ({
xMax: Math.max(acc.xMax, row.x),
xMin: Math.in(acc.xMin, row.x)
}), {xMin: Infinity, xMax: -Infinity})
```
will probably do the job?

**Comment by cmtoomey** [comment]
Thanks @mcnuttandrew - I thought that was the case. I'll make a change in my app to generate an array and pass it to the chart.
