### ISSUE TITLE
Wrapping a *Series Component

### ISSUE THREAD

**Issue by andrewrocco** [uber/react-vis#629]
For organization's sake, is there a way to wrap a `*Series` component and have it render inside a plot?

For example, I am writing a complex `LineChart` component that can display both stacked `LineSeries` and `AreaSeries` components. However, there is a lot of extra logic for styles that exists inside the `LineChart` HOC. I want this style logic to be moved to a separate component containing the `LineSeries` component.

## The HOC that houses basic react-vis charting
```jsx
// LineChart HOC
import { FlexibleWidthXYPlot } from 'react-vis';
import { SomeCustomComponent } from './SomeCustomComponent';

// data may look like this
const incomingData = [
  {
    type: 'line',
    data: [
      { x: 0, y: 0 },
      { x: 1, y: 10000 },
      { x: 2, y: 50000 },
    ],
  },
];

const renderData = () => (
  incomingData.map((datum) => {
    // I am allowing a custom data object prop to define the data type to display
    const { type } = datum;
   
    switch (type) {
      case 'line' :
        // I want this component to contain LineSeries + extra render logic
        return <SomeCustomComponent data={datum} />;
        break;
      default:
        break;
    }
  });
);

// simplified for illustrative purposes
<FlexibleWidthXYPlot>
  {renderData()}
</FlexibleWidthXYPlot>
```

## Meanwhile... in another component...
```jsx
// a wrapper component
import { LineSeries } from 'react-vis'; 
export function SomeCustomComponent({ data }) {
  const { data: seriesData } = data; // data is coming in through props (data.data)
  
  // ... lots of logic to determine how to style the line
  
  return <LineSeries data={seriesData} />;
}
```

Has anybody else tried to do this or is it not possible?

**Comment by jckr** [comment]
Hi, I think something like the LineMarkSeries component would work in your case. 
The LineMarkSeries component imports a LineSeries, and, well, a MarkSeries

It exports a new component which extends the AbstractSeries. This is important, because a lot of the logic is actually in AbstractSeries (interactions, for instance)

what it renders is a <g> element with the <LineSeries /> and the <MarkSeries /> components inside, passing them its own props with no transformation. 

But nothing prevents you from transforming these props. 
Also, a <g> element is a good way to group Series if needs be, but you can also use a custom component to render one or the other. 

For instance:

class MyCustomComponent extends AbstractSeries{
  render() {
    switch(this.props.type) {
       case 'line':
          return (<LineSeries {...this.props} strokeWidth={{this.props.isThick ? 5 : 2}} />);
       case 'area':
          return (<AreaSeries {...this.props} />);
       }
       return null;   
  }
}

does that make sense?

**Comment by andrewrocco** [comment]
@jckr It does. I'll try extending the `AbstractSeries` class and see what I can do.

Appreciate it!
