### ISSUE TITLE
can add webgl render?  i m try add, but some object no export.

### ISSUE THREAD

**Issue by dytmh** [uber/react-vis#649]
can add webgl render?  i m try add, but some object no export.

**Comment by mcnuttandrew** [comment]
It should be possible to add a WebGL rendering system, however it will take quite a bit of work (and modification to the code base!). If you follow the cues from the canvas drawing then it should be quite possible to add webgl, (this work has sort of been done before and then was removed because it made the library too heavy https://github.com/uber/react-vis/commit/028fb23c5f2e2f13f08f3f9b627bd4827174400f)

**Comment by mcnuttandrew** [comment]
I'm gonna mark this as closed, but feel free to continue the conversation under the fold if you like
