### ISSUE TITLE
Allow a single LineSeries to be styled differently between x values: zones

### ISSUE THREAD

**Issue by leonelgalan** [uber/react-vis#672]
For the lack of a better example, I first used this feature in [Highcharts (documentation)](https://www.highcharts.com/docs/chart-concepts/series#zones). The particular use case I'm interested is when displaying the current/ongoing partial month (Xf) I would use dashes from Xf-1 to Xf.

My first thought was, to simply add two LineSeries, but if I'm using curves it won't use a curve to connect the two series:

![screen shot 2017-12-01 at 10 43 14 am](https://user-images.githubusercontent.com/727774/33490358-e3d1bb0e-d684-11e7-9e29-55c0aa9aa906.png)

A solution that comes to mind is allowing props like `color` or `strokeStyle` receive both a string or a function(Xo, Xf, Yo, Yf) that returns a string?

**Comment by akre54** [comment]
Typically I use 2 different line series (because they are technically different series). Most often a projection is displayed as a line because it conveys uncertainty distinct from the rest of the data, but I also don't see an issue with allowing more properties to take accessor functions.

**Comment by jckr** [comment]
Yeah. The way to deal with this is with several <LineSeries /> elements. 
So we had a choice: 
- Either treat LineSeries as a set of individual straight segments between 2 points, in which case we could support styling per segment,
- Or treat each LineSeries as an indivisible entity. The advantage of that is that we can have interpolation functions, so that the LineSeries could become more than just a set of segments. 

We chose the 2nd route.
