### ISSUE TITLE
Guidance Positioning hint components for multuple BarSeries in same XYPlot

### ISSUE THREAD

**Issue by dan-weaver** [uber/react-vis#686]
I'm wondering how one would go about placing <Hint /> components on multiple bar series with in the same Plot.  Something like:
![hintplacement](https://user-images.githubusercontent.com/1619461/33864630-4380b556-deb3-11e7-8b58-300c7fac0e87.png)

I can't seem to find a decent solution that doesn't involve tweaking position offsets which doesn't scale when the number of x axis items changes.  Has anyone else solved this problem?

I suppose the problem I'm encountering is that Hint is rendered with the x / y value which makes complete sense. But this mean's it's completely decoupled from the rendering of individual bars within a bar series like this.

Should I be using calculated scale / domain values to determine in pixels where each hint should be "offset".  Sounds possible, but thought there may be a more elegant solution

Maybe this isn't a proper use for Hint at all? Is there another option?

**Comment by jckr** [comment]
yeah, right now the Hint doesn't have the same function as Bar Series which is automatically offset if there are several. We could come up with an API to do that, or have manual workarounds (ie through styles, through modification of the X value...)
I'm going to mark this as an enhancement for now

**Comment by tumetus** [comment]
Hi @dan-weaver @jckr !

I have been trying to figure out how to implement exactly that kind of behaviour where you can put a value on top of the bar. I tried to do this with LabelSeries by using the same data as I use to render the bars, only adding property "label" to the data. This works kind of ok, the only problem is that the LabelSeries automatically sets the text either before or after and above or below the datapoint depending on if the datapoint is closer the beginning or the end of the range. At least I couldn't find a way to set all the labels for example "middle" and "above" the datapoint. Do you know if this is currently possible? And is LabelSeries a "correct" way to approach this problem?

The values for where to set the text seems to be calculated here https://github.com/uber/react-vis/blob/71116cdeafae5db0a952d87da28e210d4dfc4018/src/plot/series/label-series.js#L73

I could work on a PR, if you think that we could add new props for the LabelSeries component say something like "yAlign" and "xAlign" so that user could for example determine that every label "above" and "middle" of the datapoint?

**Comment by dan-weaver** [comment]
awesome @tumetus!

**Comment by monaawi** [comment]
Hi, I'm having the issue described exactly in the picture above. I have the same x and different y's and I want to place labels on top middle of each bar. I don't see how the solution provided solves my issue. I can use labelAnchorX end to one series and labelAnchorX start to another but this doesn't like how I want it too. How could I place the label in the middle of each bar series in this case?

**Comment by harunurhan** [comment]
#768 won't help to put labels on top the center of each bar, or am I missing something?

**Comment by tumetus** [comment]
Hi @monaawi !

I am not sure if I understood your problem correctly, but I have been able to put labels on top center of bars with the labelAnchorX and labelAnchorY props with values labelAnchorX="middle" and labelAnchorY="text-after-edge".

I wrote a blog post which illustrates how to implement that kind of behaviour, you can check it out at https://codepulse.blog/how-to-create-a-bar-chart-with-react/ .

Not sure if this helps but let me know!  🙂

**Comment by monaawi** [comment]
Hi @tumetus !
Thank you for the quick reply. My issue is when you have two bars with the same x (multiple bar series) and I want to put a label on each one. 
I managed to make a workaround for it by using xOffset but this doesn't scale when the graph shrinks/expands.
This is what it looks like with middle and text-after-edge
![screenshot1](https://user-images.githubusercontent.com/20395298/57523689-ee451600-7325-11e9-9893-5e3426d33692.png)
This is how I want it to look like and how it looks like with the xOffset but it is not scalable
![screenshot2](https://user-images.githubusercontent.com/20395298/57523710-fc933200-7325-11e9-8563-5e26152e1fa9.png)

**Comment by tumetus** [comment]
Ok now I see what you mean. The #768 won't in fact solve that issue. 

My thinking is that if you can solve, from the react-vis code, how the bar x positions are determined when they have the same x, you could then determine the label x positions the same way.

I tried to dig through the code but could not solve how react-vis is determining the bar positions when two bars (or more) have the same x value.

**Comment by harunurhan** [comment]
Can we re-open this issue at least, because it seems to me what issue describes is not solved?
