### ISSUE TITLE
When xType is 'discrete' x coordinates are parsed as strings

### ISSUE THREAD

**Issue by idjuradj** [uber/react-vis#758]
Let's say I want to plot Bar Series in a discrete manner - bars are present only on given x coordinates. There is also one Line Series plotted over the last bar in the bar series.

It currently looks like this:
![untitled](https://user-images.githubusercontent.com/5818649/37867990-4618ba82-2fa0-11e8-9e90-fc2172873f44.png)

To avoid empty spaces at coordinates 5, 6, 7 - I set `xType` prop to `ordinal` on `XYPlot`. The problem in this case - the graph is not aware that coordinates of last line series are the same as on the last bar in the bar series.
![untitled](https://user-images.githubusercontent.com/5818649/37867993-5f44ba74-2fa0-11e8-82ae-ca4c22bcb567.png)
Seems that x coordinates are parsed as strings when `xType` is `ordinal `- is this intentional?
Do you have any suggestions on how to go around this issue?

**Comment by jckr** [comment]
That's an interesting problem. 
There are several ways to fix this. Indeed x coordinates are parsed as strings when xType is ordinal, this is intentional. There was an issue on a very similar topic this week, apologies for not replying sooner to your question as I first thought this was the same issue. 

If you want to use a LineSeries to represent the "crack" effect, you're really going to need a linear x scale anyway. So I would do something like this. 

For each of your bars, give an x value going from 0 to 4. 
For the lineSeries, do what you did but with x values around 4 instead of around 8.
So, your xDomain is effectively [0, 4]. 

how to represent ticks as 1, 2, 3, 4, 8? 
well, you can use tickFormat for that. 

you can have your bar labels as say, a labels variable labels = ['1', '2', '3', '4', '8'];
Now your XAxis will have a tickFormat prop like so: <XAxis tickFormat={(d) => labels[d]} />
so it will be displayed using the labels you chose.

Does that help?

**Comment by mcnuttandrew** [comment]
Marking as resolved, feel free to reopen if you feel differently!
