### ISSUE TITLE
y-axis labels truncated

### ISSUE THREAD

**Issue by whittlem** [uber/react-vis#833]
My graph has fairly large numbers on the y-axis. It can be up to 10 characters in some cases. It looks like the y-axis is only showing 4.5 numbers and truncating the rest from the left. How can I increase how much space is given to the label when rendering the graph?

**Comment by TheMcMurder** [comment]
@whittlem how did you solve this issue? I'm experiencing something similar.

**Comment by TheMcMurder** [comment]
See https://github.com/uber/react-vis/issues/400 for a similar issue/resolution (found this issue via search and it took me a while to find the other)

**Comment by whittlem** [comment]
Thanks for the reply. I sort of got it working like this...

<YAxis width={100} title='Price' style={axisStyle} />

It doesn't look very nice though. The margin is wider but the graph lines actually draw over the "Prices". 

I will try adjusting the margin as per your link. Thanks very much.

**Comment by whittlem** [comment]
This worked perfectly, thanks...

<XYPlot height={480} width={window.innerWidth * 0.85} margin={{left: 100}}>

**Comment by paddotk** [comment]
For others ending up on this issue like me: setting the `text-anchor: end` (css) on last value of the axis (the `text` element) was the better fix for me. This is like `text-align: right` but instead a property that works on svg elements.

**Comment by adamward84** [comment]
@paddotk how did you single out the *last* `text` element for adjustment? I also want to use the `text-anchor` method, but can't seem to get my CSS right (`:last-child` etc doesn't seem to work?). Much appreciated in advance!

**Comment by paddotk** [comment]
@adamward84 I think `.xAxis g > g:last-child text { text-anchor: end }` (where `aAxis` is the className assigned to the axis component) should do it. Note that it's not `..g text:last-child` since every `text` element is wrapped in a `g` element. 

If this doesn't work; our implementation of the axes is a specific one where (for another reason than this css property) we used several axes next to each other, to appear as one. For this we did something like the following:

In the react component:
```
const len = 5;
for (let i = 0; i < len; i++) {
  const textAnchor = (i + 1 === len) ? 'end' : 'start';
  return (
     <XAxis style={{ text: { textAnchor }
  );
}
```
You could do something similar to achieve this with the difference being that you might need only 2 x or y axes.
