### ISSUE TITLE
Move axis title outside chart

### ISSUE THREAD

**Issue by markov00** [uber/react-vis#883]
Currently the axis titles are drawn inside the chart like in the following example:
<img width="400" alt="screen shot 2018-07-18 at 09 40 35" src="https://user-images.githubusercontent.com/1421091/42867041-a6e63ff0-8a6e-11e8-84ef-d26e7b90e2d3.png">

I don't see a way to move the axis title outside the chart like in this chart:
<img width="400" alt="screen shot 2018-07-18 at 09 42 58" src="https://user-images.githubusercontent.com/1421091/42867160-01ce2540-8a6f-11e8-986d-db5f739119f6.png">

Is there anything I can do to move/translate the axis title outside the chart?

**Comment by mcnuttandrew** [comment]
There's been some questions about this type of thing before #542. I've been thinking that the API for the axis title is kinda overloaded (eg there a bunch of tags to place the label in various positions), and maybe we should introduce a new component something like <ChartLabel >, which could 
- accept a percentage or tag word (bottom-middle, top-left) 
- and an orientation. 
- It would probably be html component rather than an svg, (though it could probably be pretty easily implemented as both)
- For generality could make the label inside of the axes component use it

It would allow users to put titles on their chair in general, and just provide more options for annotations. 

Thoughts?

**Comment by dooleyb1** [comment]
Would strongly welcome this change also. Any advancements on this?

**Comment by mcnuttandrew** [comment]
I ended up implementing a ChartLabel component, I'll put out a PR for it sometime later today. It has roughly the features I described above!

**Comment by dooleyb1** [comment]
Sounds good, cheers Andrew!

**Comment by mcnuttandrew** [comment]
Now available!! Resolving
