### ISSUE TITLE
Is there a way to find the max & min value on Y-Axis?

### ISSUE THREAD

**Issue by ksairamya** [uber/react-vis#899]

**Comment by ksairamya** [comment]
@mcnuttandrew

**Comment by mcnuttandrew** [comment]
As far as I know there isn't really a good way to expose the internal domain/range/etc representation of the scales. This is because of the one way data flow pattern of react components, it hypothetically should not be the concern of upper level components what the child components are up to. When I've found myself needing to get the yDomain I just compute myself ahead of time and then specify it as a prop to XYPlot.

Example of computing y domain
```js
const {min, max} = data.reduce((acc, row) => ({
 min: Math.min(acc.min, row.y),
 max: Math.max(acc.max, row.y)
}, {min: Infinity, max: -Infinity})l
```

And then handing it to a XYPlot:

```js
<XYPlot yDomain={[min, max]} yType="linear">
    <MarkSeries data={data} />
</XYPlot>
```

It's probably not the answer you were hoping for, but I hope it helps

**Comment by ksairamya** [comment]
Thank you @mcnuttandrew
