### ISSUE TITLE
Interaction handlers event wrapped in a event object?

### ISSUE THREAD

**Issue by Stianhn** [uber/react-vis#908]
Why is the handlers event callback wrapped in a event object?
      
 <MarkSeries onValueMouseOver={(datapoint, event) => event.event...}/>

https://github.com/uber/react-vis/blob/master/docs/mark-series.md

Best Regards

**Comment by mcnuttandrew** [comment]
I think it's hypothetically so that we could add additional properties in there if we wanted later. I agree with you that it's a little odd, but given how central it is to the api i think it might be unlikely to change for a while.  I've noted this issue in the API audit thread for when we get around to making breaking changes. 

I'm going to close this issue, as it is not be covered in #821
